"""Adicionando campo justificativa na movimentacao_estoque

Revision ID: 7a42e8e6f4ea
Revises: 
Create Date: 2024-09-15 16:04:58.819635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a42e8e6f4ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacao_estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('justificativa', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacao_estoque', schema=None) as batch_op:
        batch_op.drop_column('justificativa')

    # ### end Alembic commands ###
